install.packages("Cairo", repos='https://cran.cnr.berkeley.edu/')
source("https://bioconductor.org/biocLite.R")
biocLite("ChIPseeker")
biocLite("clusterProfiler")
biocLite("TxDb.Hsapiens.UCSC.hg19.knownGene")
library("Cairo")
library("ChIPseeker")
library("clusterProfiler")
library("TxDb.Hsapiens.UCSC.hg19.knownGene")
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
files <- list.files(".", pattern = "final.bed", full.names = TRUE)
promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
tagMatrix <- lapply(files, getTagMatrix, windows=promoter)
tagMatrixList <- setNames(tagMatrix,c(files))
peakAnno <- lapply(files, annotatePeak, TxDb=txdb, tssRegion=c(-3000, 3000), verbose=FALSE)
peakAnnoList <- setNames(peakAnno,c(files))
genes = lapply(peakAnnoList, function(i) as.data.frame(i)$geneId)
names(genes) = sub("_", "\n", names(genes))
compKEGG <- compareCluster(geneCluster=genes, fun="enrichKEGG", pvalueCutoff=0.05, pAdjustMethod="BH")
png("signal.compilation.png")
plotAvgProf(tagMatrixList, xlim=c(-3000, 3000), conf=0.95,resample=1000, facet="row")
dev.off()
png("tag.heatmap.png")
tagHeatmap(tagMatrixList, xlim=c(-3000, 3000), color=NULL)
dev.off()
png("feature.distribution.png")
plotAnnoBar(peakAnnoList)
dev.off()
png("relative2tss.png")
plotAnnoBar(peakAnnoList)
dev.off()
png("kegg.png")
plot(compKEGG, showCategory=15, title="KEGG Pathway Enrichment Analysis")
dev.off()
